const vaults = [
    {
      id: 1,
      name: "Spark DAI Vault",
      icon: "🟠",
      token: "DAI",
      tokenIcon: "🟠",
      totalSupply: "550,536,111.22 DAI",
      totalSupplyUsd: "$550.57M",
      instantApy: "5.38%",
      vaultApy: "5.38%",
      curator: "SparkDAO",
      curatorIcon: "⚡️",
      collateral: ["🔵", "🟣", "🟠"],
      rewards: "+1.16%",
      performanceFee: "0%",
    },
    {
      id: 2,
      name: "MEV Capital Usual USDC",
      icon: "🔵",
      token: "USDC",
      tokenIcon: "🔵",
      totalSupply: "322,956,538.41 USDC",
      totalSupplyUsd: "$322.87M",
      instantApy: "6.41%",
      vaultApy: "5.25%",
      curator: "MEV Capital",
      curatorIcon: "⚡️",
      collateral: ["🟢", "🔴", "🔵", "+13"],
      rewards: "+1.16%",
      performanceFee: "10%",
    },
    {
      id: 3,
      name: "Steakhouse USDC",
      icon: "🔵",
      token: "USDC",
      tokenIcon: "🔵",
      totalSupply: "113,948,063.12 USDC",
      totalSupplyUsd: "$113.94M",
      instantApy: "6.78%",
      vaultApy: "5.36%",
      curator: "Steakhouse Financial",
      curatorIcon: "🥩",
      collateral: ["🟡", "🔵", "🟢", "+7"],
      rewards: "+1.16%",
      performanceFee: "5%",
    },
    {
      id: 4,
      name: "Smokehouse USDC",
      icon: "🔵",
      token: "USDC",
      tokenIcon: "🔵",
      totalSupply: "104,908,784.12 USDC",
      totalSupplyUsd: "$104.87M",
      instantApy: "5.76%",
      vaultApy: "4.60%",
      curator: "Steakhouse Financial",
      curatorIcon: "🥩",
      collateral: ["🟡", "🔵", "🟢"],
      rewards: "+1.16%",
      performanceFee: "5%",
    },
    {
      id: 5,
      name: "Steakhouse RUSD",
      icon: "🟠",
      token: "rUSD",
      tokenIcon: "🟠",
      totalSupply: "89,888,265.90 rUSD",
      totalSupplyUsd: "$89.86M",
      instantApy: "7.19%",
      vaultApy: "6.03%",
      curator: "Steakhouse Financial",
      curatorIcon: "🥩",
      collateral: ["🟡", "🔵", "🟢"],
      rewards: "+1.16%",
      performanceFee: "5%",
    },
    {
      id: 6,
      name: "Gauntlet USDC Core",
      icon: "🔵",
      token: "USDC",
      tokenIcon: "🔵",
      totalSupply: "83,017,026.08 USDC",
      totalSupplyUsd: "$82.96M",
      instantApy: "5.69%",
      vaultApy: "5.12%",
      curator: "Gauntlet",
      curatorIcon: "🛡️",
      collateral: ["🟡", "🔵", "🟢", "+9"],
      rewards: "+1.16%",
      performanceFee: "10%",
    },
    {
      id: 7,
      name: "Hakutora USDC",
      icon: "🔵",
      token: "USDC",
      tokenIcon: "🔵",
      totalSupply: "52,719,107.98 USDC",
      totalSupplyUsd: "$52.71M",
      instantApy: "5.34%",
      vaultApy: "4.27%",
      curator: "Hakutora",
      curatorIcon: "🐯",
      collateral: ["🟢", "🔵", "🟣"],
      rewards: "+1.16%",
      performanceFee: "0%",
    },
    {
      id: 8,
      name: "Gauntlet WETH Prime",
      icon: "🟣",
      token: "WETH",
      tokenIcon: "🟣",
      totalSupply: "29,157.98 WETH",
      totalSupplyUsd: "$83.82M",
      instantApy: "3.76%",
      vaultApy: "2.89%",
      curator: "Gauntlet",
      curatorIcon: "🛡️",
      collateral: ["🟡", "🔵", "🟢", "+9"],
      rewards: "+1.16%",
      performanceFee: "10%",
    },
    {
      id: 9,
      name: "Steakhouse USDT",
      icon: "🟢",
      token: "USDT",
      tokenIcon: "🟢",
      totalSupply: "52,453,172.01 USDT",
      totalSupplyUsd: "$52.45M",
      instantApy: "4.74%",
      vaultApy: "3.36%",
      curator: "Steakhouse Financial",
      curatorIcon: "🥩",
      collateral: ["🟡", "🔵"],
      rewards: "+1.16%",
      performanceFee: "5%",
    },
    {
      id: 10,
      name: "Gauntlet LBTC Core",
      icon: "🟡",
      token: "LBTC",
      tokenIcon: "🟡",
      totalSupply: "589.45 LBTC",
      totalSupplyUsd: "$32.80M",
      instantApy: "3.58%",
      vaultApy: "1.92%",
      curator: "Gauntlet",
      curatorIcon: "🛡️",
      collateral: ["🟡", "🔵", "🟢"],
      rewards: "+1.16%",
      performanceFee: "10%",
    },
  ];
  
  export default vaults;
  