const vaults = [
  {
    id: 1,
    name: "Spark DAI Vault",
    icon: "🟠",
    token: "DAI",
    tokenIcon: "🟠",
    totalSupply: "550,536,111.22 DAI",
    totalSupplyUsd: "$550.57M",
    instantApy: "5.38%",
    vaultApy: "5.38%",
    curator: "SparkDAO",
    curatorIcon: "⚡️",
    collateral: ["🔵", "🟣", "🟠"],
    rewards: "+1.16%",
    performanceFee: "0%",
  },
  {
    id: 2,
    name: "MEV Capital Usual USDC",
    icon: "🔵",
    token: "USDC",
    tokenIcon: "🔵",
    totalSupply: "322,956,538.41 USDC",
    totalSupplyUsd: "$322.87M",
    instantApy: "6.41%",
    vaultApy: "5.25%",
    curator: "MEV Capital",
    curatorIcon: "⚡️",
    collateral: ["🟢", "🔴", "🔵", "+13"],
    rewards: "+1.16%",
    performanceFee: "10%",
  },
  {
    id: 3,
    name: "Steakhouse USDC",
    icon: "🔵",
    token: "USDC",
    tokenIcon: "🔵",
    totalSupply: "113,948,063.12 USDC",
    totalSupplyUsd: "$113.94M",
    instantApy: "6.78%",
    vaultApy: "5.36%",
    curator: "Steakhouse Financial",
    curatorIcon: "🥩",
    collateral: ["🟡", "🔵", "🟢", "+7"],
    rewards: "+1.16%",
    performanceFee: "5%",
  },
  {
    id: 4,
    name: "Smokehouse USDC",
    icon: "🔵",
    token: "USDC",
    tokenIcon: "🔵",
    totalSupply: "104,908,784.12 USDC",
    totalSupplyUsd: "$104.87M",
    instantApy: "5.76%",
    vaultApy: "4.60%",
    curator: "Steakhouse Financial",
    curatorIcon: "🥩",
    collateral: ["🟡", "🔵", "🟢"],
    rewards: "+1.16%",
    performanceFee: "5%",
  },
  {
    id: 5,
    name: "Steakhouse RUSD",
    icon: "🟠",
    token: "rUSD",
    tokenIcon: "🟠",
    totalSupply: "89,888,265.90 rUSD",
    totalSupplyUsd: "$89.86M",
    instantApy: "7.19%",
    vaultApy: "6.03%",
    curator: "Steakhouse Financial",
    curatorIcon: "🥩",
    collateral: ["🟡", "🔵", "🟢"],
    rewards: "+1.16%",
    performanceFee: "5%",
  },
  {
    id: 6,
    name: "Gauntlet USDC Core",
    icon: "🔵",
    token: "USDC",
    tokenIcon: "🔵",
    totalSupply: "83,017,026.08 USDC",
    totalSupplyUsd: "$82.96M",
    instantApy: "5.69%",
    vaultApy: "5.12%",
    curator: "Gauntlet",
    curatorIcon: "🛡️",
    collateral: ["🟡", "🔵", "🟢", "+9"],
    rewards: "+1.16%",
    performanceFee: "10%",
  },
  {
    id: 7,
    name: "Hakutora USDC",
    icon: "🔵",
    token: "USDC",
    tokenIcon: "🔵",
    totalSupply: "52,719,107.98 USDC",
    totalSupplyUsd: "$52.71M",
    instantApy: "5.34%",
    vaultApy: "4.27%",
    curator: "Hakutora",
    curatorIcon: "🐯",
    collateral: ["🟢", "🔵", "🟣"],
    rewards: "+1.16%",
    performanceFee: "0%",
  },
  {
    id: 8,
    name: "Gauntlet WETH Prime",
    icon: "🟣",
    token: "WETH",
    tokenIcon: "🟣",
    totalSupply: "29,157.98 WETH",
    totalSupplyUsd: "$83.82M",
    instantApy: "3.76%",
    vaultApy: "2.89%",
    curator: "Gauntlet",
    curatorIcon: "🛡️",
    collateral: ["🟡", "🔵", "🟢", "+9"],
    rewards: "+1.16%",
    performanceFee: "10%",
  },
  {
    id: 9,
    name: "Steakhouse USDT",
    icon: "🟢",
    token: "USDT",
    tokenIcon: "🟢",
    totalSupply: "52,453,172.01 USDT",
    totalSupplyUsd: "$52.45M",
    instantApy: "4.74%",
    vaultApy: "3.36%",
    curator: "Steakhouse Financial",
    curatorIcon: "🥩",
    collateral: ["🟡", "🔵"],
    rewards: "+1.16%",
    performanceFee: "5%",
  },
  {
    id: 10,
    name: "Gauntlet LBTC Core",
    icon: "🟡",
    token: "LBTC",
    tokenIcon: "🟡",
    totalSupply: "589.45 LBTC",
    totalSupplyUsd: "$32.80M",
    instantApy: "3.58%",
    vaultApy: "1.92%",
    curator: "Gauntlet",
    curatorIcon: "🛡️",
    collateral: ["🟡", "🔵", "🟢"],
    rewards: "+1.16%",
    performanceFee: "10%",
  },
];

export interface Project {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export const projects: Project[] = [
  {
    id: "aragon",
    name: "Aragon",
    description:
      "Building full-stack DAO technology, enabling organizations to govern their protocols and assets on-chain.",
    icon: "aragon",
  },
  {
    id: "brahma-console",
    name: "Brahma Console",
    description:
      "Console is your universal multi-chain account to secure, navigate, and automate on-chain interactions.",
    icon: "brahma",
  },
  {
    id: "contango",
    name: "Contango",
    description:
      "Trade decentralized perpetual futures by automated hedging strategies on underlying lending protocols.",
    icon: "contango",
  },
  {
    id: "delv-fixed-borrow",
    name: "DELV Fixed Borrow",
    description:
      "DELV Fixed Borrow enables existing DeFi borrowers on Morpho to fix their interest rates and gain predictability on borrow costs.",
    icon: "hyperdrive",
  },
  {
    id: "defi-saver",
    name: "Defi Saver",
    description:
      "Advanced DeFi Management. All the essential tools for creating, tracking, and managing your DeFi portfolio.",
    icon: "defisaver",
  },
  {
    id: "definitive",
    name: "Definitive",
    description:
      "A non-custodial platform for advanced on-chain trade execution and DeFi yield.",
    icon: "definitive",
  },
  {
    id: "furucombo",
    name: "Furucombo",
    description:
      "Furucombo is a multi-chain DeFi aggregator designed to simplify & optimize DeFi trading for everyone!",
    icon: "furucombo",
  },
  {
    id: "hyperdrive",
    name: "Hyperdrive",
    description:
      "Get yield, your way. Access fixed and variable yields at your control with Hyperdrive.",
    icon: "hyperdrive",
  },
  {
    id: "idle-finance",
    name: "Idle Finance",
    description:
      "Yield optimization and risk tranching. Automated, diversified, DeFi yields.",
    icon: "idlefinance",
  },
  {
    id: "instadapp",
    name: "Instadapp",
    description:
      "The ultimate DeFi hub. Simplify your journey and enjoy a safer, more accessible experience.",
    icon: "instadapp",
  },
  {
    id: "ionic-protocol",
    name: "Ionic Protocol",
    description:
      "Isolated Lending and Borrowing for Yield Bearing Assets on the Superchain.",
    icon: "ionic",
  },
  {
    id: "moonwell",
    name: "Moonwell",
    description:
      "Put your digital assets to work. Lend or borrow to handle whatever life throws your way.",
    icon: "moonwell",
  },
  {
    id: "opencover",
    name: "OpenCover",
    description:
      "The leading cover aggregator to protect your portfolio against protocol risk.",
    icon: "opencover",
  },
  {
    id: "origami",
    name: "Origami",
    description: "Automated leverage for dummies.",
    icon: "origami",
  },
  {
    id: "oval",
    name: "Oval",
    description: "Capture OEV from liquidations.",
    icon: "oval",
  },
  {
    id: "protocolink",
    name: "Protocolink",
    description: "Linking the potential of Web3 using the most elastic SDK.",
    icon: "protocolink",
  },
  {
    id: "reserve",
    name: "Reserve",
    description:
      "A permissionless platform to launch and govern R1 asset-backed currencies.",
    icon: "reserve",
  },
  {
    id: "safe",
    name: "Safe",
    description: "The most trusted Smart Wallet.",
    icon: "safe",
  },
  {
    id: "sommelier-finance",
    name: "Sommelier Finance",
    description:
      "Automated vaults to find best-in-class yields while mitigating risk.",
    icon: "sommelier",
  },
  {
    id: "stream",
    name: "Stream",
    description: "A capital-efficient platform to supercharge DeFi adoption.",
    icon: "stream",
  },
  {
    id: "summerfi",
    name: "SummerFi",
    description:
      "Power up your portfolio by Borrowing, Lending, and Multiplying your favorite assets using automated tools.",
    icon: "summerfi",
  },
  {
    id: "superform",
    name: "Superform",
    description: "The Onchain Wealth App",
    icon: "superform",
  },
  {
    id: "vaultcraft",
    name: "VaultCraft",
    description:
      "Leading modular DeFi and RTCI vault protocol - now powered by Gnosis Safe.",
    icon: "vaultcraft",
  },
];

export default vaults;
